swdcom for Linux and zeptoforth
Crest/swdcom pull request #1
Opened 2020-06-12 04:39 UTC by tabemann

Here are some changes to swdcom for supporting Linux and zeptoforth (the Linux changes are in swd2.c and Makefile, the zeptoforth support is in bootstrap_zepto.fs). Reconciling swd2.c and Makefile so single files can work with both Linux and FreeBSD should not be too hard, whereas bootstrap_zepto.fs is a separate file not needing merging.

2020-06-13 21:42 UTC, Crest commented
The `#include <time.h>` isn't optional. Both the Linux and FreeBSD manual pages stat that `time.h` has to be included to use `clock_gettime()`. Some other header  already includes `time.h` on your system but that isn't an assumption I'm willing to make.

2020-06-14 01:37 UTC, tabemann commented
I know that `#include <time.h>` isn't optional. Rather, matter is that in my code I somehow ended up with two copies of the `#include`.

2020-06-14 21:23 UTC, Crest commented
I would prefer a `#ifdef` from CLOCK_MONOTONIC_FAST to CLOCK_MONOTONIC_COARSE instead of an explicit mention of Linux. That way the code would work on other platforms as long as they provide at one.

2020-06-14 21:45 UTC, tabemann commented
CLOCK_MONOTONIC_COARSE is Linux-specific, for the record.

On Sun, Jun 14, 2020, 16:23 Crest <notifications@github.com> wrote:

> I would prefer a #ifdef from CLOCK_MONOTONIC_FAST to
> CLOCK_MONOTONIC_COARSE instead of an explicit mention of Linux. That way
> the code would work on other platforms as long as they provide at one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Crest/swdcom/pull/1#issuecomment-643823991>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDMC2DKCJTGVNGFEOCIM73RWU5UBANCNFSM4N37RLHQ>
> .
>

2020-06-21 21:01 UTC, Crest requested changes
Please leave the Makefile unchanged and only change the GNUmakefile if you have to.

2020-06-21 21:32 UTC, tabemann commented
The changes are now in their proper state, with only changes being made to bootstrap_zepto.fs .

2020-06-21 21:41 UTC, Crest approved these changes
Looks good.

2020-06-21 21:42 UTC, merged